var buffer = ["#0","#1","#2","#3","#4","#5"];
var curCel = ['bgs/1.jpg','bgs/clouds.png','','grounds/0.png','','girls/0.png'];
var page = [['bgs/2.jpg','','','','','bgs/construction.png'],""];
var page0 = [curCel.slice(),"<h2>Once upon a time</h2>, there was a little girl with rosy cheeks and a sweet smile.",0,5];
var page1 = [['bgs/1.jpg','bgs/clouds1.png','houses/1.png','grounds/1.png','otherChars/parents.png','girls/1.png'],
	"She lived happily with her parents in a cozy cottage on the edge of town.",55,10];
var page2 = [page1[0].slice(),"One day, her mother and father grew sick and could not leave the bed.",55,10];
	page2[0][4]= ""; page2[0][5]='girls/2.png';
var page3 = [page2[0].slice(),"The little girl did her best to care for them, but soon it was clear they needed a doctor.",55,10];
var page4 = [page2[0].slice(),"The family had little money to their name, and the nearest doctor lived very far away. The little girl was afraid there was not enough money to pay for the doctor and his travel.",55,10];
	page4[0][5] = 'girls/3.png';
var page5 = [['bgs/1.jpg','bgs/clouds2.png','houses/2.png','grounds/2.png','','girls/cry.png'],"Not knowing what else to do, she started to cry.",18,8];
var page6 = [page5[0].slice(),"A passing crow, hearing her quiet sobs and seeing her tears, landed beside her.",18,8];
	page6[0][4]="otherChars/crow.png";
var page7 = [page6[0].slice(),"<h2>“Why are you crying?”</h2> asked the crow.",18,8];
	page7[0][4] ="otherChars/crow2.png";
var page8 = [page7[0].slice(),"<h2>“My parents are ill and I do not have the money to pay for a doctor. And I am afraid to travel so far on my own.”</h2> said the little girl.",18,8];
	page8[0][4] = "otherChars/crow3.png"; page8[0][5] = "girls/cry2.png";
var page9 = [page8[0].slice(),"<h2>“Take courage and have faith.”</h2> said the crow. <h2>“There are those who still know to share with those who have little.”</h2>",18,8];
	page9[0][4] = "otherChars/crow2.png"; page9[0][5]="girls/cry3.png";
var page10 = [page9[0].slice(),"Reaching into his pocket, the crow gave the little girl a small loaf of bread.",18,8];
	page10[0][5]="otherChars/crow4.png"; page10[0][4] = "girls/cryReach.png";
var page11 = [['bgs/1.jpg','bgs/clouds.png','','grounds/3.png','','girls/bread.png'],"The little girl was touched by the crow’s kindness, and took courage from the gesture. She decided that the trip through the woods to the doctor’s house was not too far, after all.",18,2];
var page12 = [page8[0].slice(),"So the little girl put on her <h2>scarf</h2>, and with her loaf of <h2>bread</h2> in hand, she waved goodbye to the kind <h2>crow</h2> and set off down the little road.",18,8];
	page12[0][5]="girls/walk.png";
var page13 = [['bgs/1.jpg','grounds/4.png','houses/town1.png','houses/town2.png','otherChars/hog1.png','girls/town1.png'],"By and by, she came upon a <h2>hedgehog</h2> begging by the side of the road.",68,25];
var page14 = [page13[0].slice(),"<h2>“I am so hungry”</h2> said the hedgehog, <h2>“and I have children at home to feed.”</h2>",68,25];
	page14[0][4] = 'otherChars/hog2.png';
var page15 = [page13[0].slice(),"The young girl thought of her little loaf of bread, and how <h2>hungry</h2> she would be without it.",68,25];
	page15[0][5] = 'girls/town2.png';
var page16 = [page15[0].slice(),"But, she told herself the <h2>hedgehog</h2> needed the bread more than she did, and handed it to her.",65,25];
	page16[0][4] = 'otherChars/hog3.png'; page16[0][5]='girls/town3.png';
var page17 = [['bgs/1.jpg','grounds/5.png','girls/town4.png','houses/town3.png','','otherChars/hog4.png'],"The hedgehog wept for joy,thanked her, and left to share the meal with her children.",0,5];
var page18 = [['bgs/3.jpg','bgs/clouds3.png','grounds/6.png','houses/rock1.png','otherChars/bunny1.png','girls/hill1.png'],"Over the next hill, the little girl came across a small bunny huddled next to a large rock.",3,45];
var page19 = [page18[0].slice(),"He had no hat or shawl for his ears and shivered hard each time the cold wind blew.",3,45];
	page19[0][5]='girls/hill2.png';
var page20 = [page19[0].slice(),"The little girl thought of her warm scarf, and how cold she would feel without it. ",3,45];
	page20[0][5] = 'girls/hill3.png';
var page21 = [page20[0].slice(),"She told herself that she was older and bigger than the little bunny and could better withstand the cold. So she gave the little bunny her scarf.",3,45];
	page21[0][4] = 'otherChars/bunny2.png'; page21[0][5] = 'girls/hill4.png';
var page22 = [['bgs/3.jpg','bgs/clouds3.png','grounds/7.png','houses/rock2.png','otherChars/bunny3.png','girls/hill5.png'],"The bunny wrapped his little ears under the scarf and thanked her for her kindness. The little girl walked on.",3,45];
var page23 = [['bgs/4.jpg','bgs/woods1.png','grounds/town1.png','houses/townBack.png','houses/townFront.png','girls/2town1.png'],"Soon, the little girl came upon a little town. Past the rooftops, she could see the trees of the great woods. The doctor lived just on the other side of them.",7,45];
var page24 = [['bgs/4.jpg','bgs/woods2.png','grounds/town2.png','houses/townShop.png','otherChars/cat1.png','girls/2town2.png'],"As she neared the far edge of town, the little girl noticed a young cat staring into a shop window.",7,45];
var page25 = [page24[0].slice(),"In the window were pretty dresses with lace and ribbons. The little cat’s dress was more holes than fabric, and each gust of wind seemed ready to blow it off her.",7,45];
var page26 = [page25[0].slice(),"The little girl thought of her own pretty frock and the ones she had hanging in her closet at home. She thought of how silly she would look walking around in just her shift.",7,45];
	page26[0][5]='girls/2town3.png';
var page27 = [page26[0].slice(),"She told herself that she would soon be in the woods and the night would be too dark for anyone to see her. The young cat needed it more, so the little girl gave the cat her frock.",7,45];
	page27[0][4]='otherChars/cat2.png'; page27[0][5]='girls/2town4.png';
var page28 = [page[0].slice(),"The little cat leapt for joy and rushed off to put on the dress. The little girl smiled and walked on."];
var page29 = [page[0].slice(),"At last the little girl came upon the great woods. She shivered as she looked up at the moon and stars."];
var page30 = [page[0].slice(),"Far, far above her, the stars twinkled and sparkled in the night sky. The woods were dark, but the stars lit a small path for the girl to travel on."];
var page31 = [page[0].slice(),"As the little girl entered a small clearing, the crow flew down and landed on a boulder beside her."];
var page32 = [page[0].slice(),"“You have a kind heart.” said the crow. “To share what you have with those who have little. To give kindness without the promise of reward is a great thing, and one day, someone might do the same for you.”"];
var page33 = [page[0].slice(),"The crow took flight and flew high, high, high into the night sky, till he disappeared among the stars."];
var page34 = [page[0].slice(),"As the little girl watched, a star jumped from the night sky and streaked toward her, then another, and another."];
var page35 = [page[0].slice(),"As the light of the stars hit upon her, the little girl looked down and found herself wearing a dress made of the finest cloth that seemed to sparkle with starlight."];
var page36 = [page[0].slice(),"Delighted, the little girl held the dress to collect the stars that were still falling into her lap."];
var page37 = [page[0].slice(),"Each star clinked as it landed and she found that the stars had become gold coins as they fell."];
var page38 = [page[0].slice(),"The little girl rejoiced and thanked the stars for their gift."];
var page39 = [page[0].slice(),"The girl fetched the doctor and brought him back to her parents. They were soon healthy again and were so proud of their kind and giving daughter."];
var page40 = [page[0].slice(),"Thanks to the star’s gift, the three of them lived comfortably and happily for the rest of their days."]
var pages = [page0,page1,page2,page3,page4,page5,page6,page7,page8,page9,page10,page11,page12,page13,page14,page15,page16,page17,page18,page19,page20,
			page21,page22,page23,page24,page25,page26,page27,page28,page29,page30,page31,page32,page33,page34,page35,page36,page37,page38,page39,page40];
var index = 0;
var scene = document.getElementById('scene');
var parallax = new Parallax(scene);